name: DevSecOpsapp
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: BUILD
      run: echo Run Build
    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    needs: build
    steps:
      - name: Deploy Dev
        run: echo Deploy on Dev environment is Done!
  
  deploy-sast:
    name: SAST
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Horusec
        run: |
          git clone https://github.com/fagner-fmlo/studySecurityPipeline-DevSecOps.git
          cd studySecurityPipeline-DevSecOps/
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" 
  
  deploy-homolog:
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: 'https://google.com.br'
    needs: [deploy-dev, deploy-sast]
    steps:
      - name: Deploy on Homolog
        run: echo Deploy on Homolog environment is Done!
  
  deploy-dast:
    runs-on: ubuntu-latest
    environment:
      name: dast
    needs: deploy-homolog
    steps:
    - name: Run OWASP ZAP
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'https://google.com.br'
 
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs: [deploy-homolog, deploy-dast]
    steps:
      - name: Deploy Prod
        run: echo Deploy on Prod environment is Done!
        
