name: DevSecOpsapp
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Rodando o Build
      run: echo Build deu bom
    
  deploy-dev:
    runs-on: ubuntu-20.04
    environment:
      name: dev
    needs: build
    steps:
      - name: Rodando deploy DEV
        run: echo Deploy DEV deu bom
  
  deploy-sast:
    name: Horusec SAST
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Rodando o Horusec
        run: |
          git clone https://github.com/crypto-br/SecPipelineDemo.git
          cd SecPipelineDemo/
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" 
  
  deploy-homolog:
    runs-on: ubuntu-20.04
    environment:
      name: hml
      url: 'https://google.com.br'
    needs: [deploy-dev, deploy-sast]
    steps:
      - name: Rodando deploy HML
        run: echo Deploy HML deu bom
 
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: deploy-homolog
    steps:
      - name: Rodando deploy PRD
        run: echo Deploy PRD deu bom
        
