name: DevSecOpsapp
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Build
      run: echo Build realizado com sucesso!
      
  deploy-dev:
    runs-on: ubuntu-20.04            
    environment:
      name: dev
    needs: build
    steps:
      - name: Deploy Dev
        run: echo Deploy Dev realizado com sucesso!
        
  deploy-sast:
    runs-on: ubuntu-20.04
    environment:
      name: sast
    needs: build
    steps:
    - name: Executando o HoruSec
      run:
        sudo apt-get install git -y
        sudo git clone https://github.com/fagner-fmlo/studySecurityPipeline-DevSecOps.git
        sudo cd studySecurityPipeline-DevSecOps/
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash
        horusec start -p="./" 
        
  deploy-homolog:
    runs-on: ubuntu-20.04
    environment:
      name: homolog
    needs: deploy-dev
    steps:
    - name: Deploy Homolog
      run: echo Deploy Homolog realizado com sucesso!
  
  deploy-prod:
    runs-on: ubuntu-20.04
    environment:
      name: prod
    needs: deploy-homolog
    steps:
    - name: Deploy Prod
      run: echo Deploy Prod realizado com sucesso!
      
        
  
